GET http://localhost:3000/user/me

###
POST http://localhost:3000/user/register
Content-Type: application/json
Authorization: Basic user@test.com:pass123

###
POST http://localhost:3000/user/login
Content-Type: application/json
Authorization: Basic user@test.com:pass123

###
GET http://localhost:3000/user/logout

###
DELETE http://localhost:3000/user/remove
Content-Type: application/json

{
  "id": "664cdd9fa192e18ccf1fa435"
}