GET http://localhost:3000/user/me

###
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "username": "user@test.com",
  "password": "pass123"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json
Authorization: Basic user@test.com:pass123

###
GET http://localhost:3000/user/logout

###
DELETE http://localhost:3000/user/remove
Content-Type: application/json

{
  "id": "664b8c361b5eed69d1cbd12b"
}